/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "P_aliases.h"
#include "P.h"
#include "Echo_1_aliases.h"
#include "Echo_1.h"
#include "LED_F_aliases.h"
#include "LED_F.h"
#include "LED_D_aliases.h"
#include "LED_D.h"
#include "Segmento_aliases.h"
#include "Segmento.h"
#include "UART_RX_ISR.h"
#include "S_aliases.h"
#include "S.h"
#include "V1_aliases.h"
#include "V1.h"
#include "V2_aliases.h"
#include "V2.h"
#include "Clk_100Hz.h"
#include "Timer_Selector.h"
#include "irq_Activacion_triger.h"
#include "Trigger_out.h"
#include "Contador_Estado.h"
#include "Echo_4_aliases.h"
#include "Echo_4.h"
#include "Echo_3_aliases.h"
#include "Echo_3.h"
#include "Echo_2_aliases.h"
#include "Echo_2.h"
#include "irq_Activacion_Lectura.h"
#include "Clk2.h"
#include "Timer_Lectura.h"
#include "Clk_200Hz.h"
#include "irq_P.h"
#include "UART_Atmega.h"
#include "t1_aliases.h"
#include "t1.h"
#include "t2_aliases.h"
#include "t2.h"
#include "t4_aliases.h"
#include "t4.h"
#include "t3_aliases.h"
#include "t3.h"
#include "UART_Atmega_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

